export const sinkData = [
  {
    id: 1,  
    image: "/Images/sink/sink1.jpg",
    title: "Sink 1",
    description: "Elegant and modern sink design.",
    price: "Rs.8000",
    },
    {
    id: 2,  
    image: "/Images/sink/sink2.jpg",
    title: "Sink 2",    
    description: "Stylish sink with a sleek finish.",
    price: "Rs.20000",
    },
    {
    id: 3,  
    image: "/Images/sink/sink3.jpg",
    title: "Sink 3",    
    description: "Classic sink design.",
    price: "Rs.22250",
    },
    {
    id: 4,
    image: "/Images/sink/sink4.jpg",
    title: "Sink 4",
    description: "Compact and functional sink.", 
    price: "Rs.36000",
    },
    {
    id: 5,
    image: "/Images/sink/sink5.jpg",
    title: "Sink 5",
    description: "Luxurious sink with intricate detailing.",
    price: "Rs.33350",
    },
    {
    id: 6,
    image: "/Images/sink/sink6.jpg",
    title: "Sink 6",
    description: "Modern sink with a minimalist design.",
    price: "Rs.15000",
    },
    {
    id: 7,  
    image: "/Images/sink/sink7.jpg",
    title: "Sink 7",
    description: "Stylish sink with a contemporary look.",
    price: "Rs.18000",
    },      
    {
    id: 8,  
    image: "/Images/sink/sink8.jpg",    
    title: "Sink 8",
    description: "Elegant sink with a polished finish.",
    price: "Rs.25000",  
    },
    {
    id: 9,  
    image: "/Images/sink/sink9.jpg",
    title: "Sink 9",
    description: "Functional sink with a modern touch.",
    price: "Rs.12000",
    },  
    {
    id: 10,  
    image: "/Images/sink/sink10.jpg",
    title: "Sink 10",
    description: "Sleek sink with a contemporary design.",
    price: "Rs.14000",
  },
];  